version: '3.8'

services:
  feature_backend:
    container_name: feature_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - feature_network
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - feature_network

networks:
  feature_network:

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
